sudo: required

services:
  - docker

before_install:
  - docker build --no-cache -t unidata/thredds-docker:latest .
  - docker run --name thredds -v `pwd`/.travis:/travis -d -p 8080:8080 unidata/thredds-docker:latest
  # Give chance for TDS to fire up
  - nc -z -w300 127.0.0.1 8080
  - for i in {1..5}; do curl -o /dev/null http://127.0.0.1:8080/thredds/catalog.html && break || (echo sleeping 15... && sleep 15); done

script:
  - ./.travis/test.sh
  - docker exec thredds grep -ir severe logs/ || echo no severe catalina log entries
  - docker exec thredds grep -ir severe content/thredds/logs/ || echo no severe thredds log entries
  - docker exec thredds grep -ir warn content/thredds/logs/ || echo no warn thredds log entries
